struct PointLightData { position: vec4<f32>, color: vec4<f32> }
struct SpotLightData { position: vec4<f32>, direction: vec4<f32>, color: vec4<f32>, cone: vec4<f32> }
struct LightingUniforms { camera_pos: vec4<f32>, light_direction: vec4<f32>, light_color: vec4<f32>, ambient_color: vec4<f32>, inv_vp: mat4x4<f32>, screen_size: vec4<f32>, point_lights: array<PointLightData, 128>, spot_lights: array<SpotLightData, 32>, num_point_lights: vec4<f32>, num_spot_lights: vec4<f32> }
@group(0) @binding(0) var gbuffer_albedo: texture_2d<f32>; @group(0) @binding(1) var gbuffer_normal_roughness: texture_2d<f32>; @group(0) @binding(2) var gbuffer_material: texture_2d<f32>; @group(0) @binding(3) var gbuffer_depth: texture_depth_2d; @group(0) @binding(4) var gbuffer_sampler: sampler; @group(0) @binding(5) var<uniform> lighting: LightingUniforms;
struct VertexOutput { @builtin(position) position: vec4<f32>, @location(0) uv: vec2<f32> }
@vertex fn vs_main(@builtin(vertex_index) id: u32) -> VertexOutput { let x = f32(i32(id) / 2) * 4.0 - 1.0; let y = f32(i32(id) % 2) * 4.0 - 1.0; var out: VertexOutput; out.position = vec4<f32>(x, y, 0.0, 1.0); out.uv = vec2<f32>(x * 0.5 + 0.5, -y * 0.5 + 0.5); return out; }
const PI: f32 = 3.14159265359;
fn distribution_ggx(N: vec3<f32>, H: vec3<f32>, r: f32) -> f32 { let a = r*r; let a2 = a*a; let d = max(dot(N,H),0.0); let d2 = d*d; let dn = d2*(a2-1.0)+1.0; return a2/(PI*dn*dn); }
fn geometry_schlick_ggx(NdV: f32, r: f32) -> f32 { let rr = r+1.0; let k = (rr*rr)/8.0; return NdV/(NdV*(1.0-k)+k); }
fn geometry_smith(N: vec3<f32>, V: vec3<f32>, L: vec3<f32>, r: f32) -> f32 { return geometry_schlick_ggx(max(dot(N,V),0.0),r)*geometry_schlick_ggx(max(dot(N,L),0.0),r); }
fn fresnel_schlick(ct: f32, F0: vec3<f32>) -> vec3<f32> { return F0+(1.0-F0)*pow(clamp(1.0-ct,0.0,1.0),5.0); }
fn reconstruct_world_pos(uv: vec2<f32>, depth: f32) -> vec3<f32> { let c = vec4<f32>(uv.x*2.0-1.0,(1.0-uv.y)*2.0-1.0,depth,1.0); let w = lighting.inv_vp*c; return w.xyz/w.w; }
fn eval_light(N: vec3<f32>, V: vec3<f32>, L: vec3<f32>, rad: vec3<f32>, alb: vec3<f32>, met: f32, rou: f32, F0: vec3<f32>) -> vec3<f32> { let H = normalize(V+L); let NdL = max(dot(N,L),0.0); let D = distribution_ggx(N,H,rou); let G = geometry_smith(N,V,L,rou); let F = fresnel_schlick(max(dot(H,V),0.0),F0); let spec = (D*G*F)/(4.0*max(dot(N,V),0.0)*NdL+0.0001); let kD = (vec3<f32>(1.0)-F)*(1.0-met); return (kD*alb/PI+spec)*rad*NdL; }
@fragment fn fs_main(in: VertexOutput) -> @location(0) vec4<f32> { let as_ = textureSample(gbuffer_albedo, gbuffer_sampler, in.uv); let alb = as_.rgb; let nr = textureSample(gbuffer_normal_roughness, gbuffer_sampler, in.uv); let N = normalize(nr.rgb*2.0-1.0); let rou = max(nr.a, 0.04); let ms = textureSample(gbuffer_material, gbuffer_sampler, in.uv); let met = ms.r; let ao = ms.g; let ef = ms.b; let dep = textureSample(gbuffer_depth, gbuffer_sampler, in.uv); let wp = reconstruct_world_pos(in.uv, dep); if dep >= 1.0 { return vec4<f32>(0.0,0.0,0.0,0.0); } let V = normalize(lighting.camera_pos.xyz-wp); let F0 = mix(vec3<f32>(0.04), alb, met); let Ld = normalize(-lighting.light_direction.xyz); var Lo = eval_light(N,V,Ld,lighting.light_color.rgb*lighting.light_color.w,alb,met,rou,F0); let np = i32(lighting.num_point_lights.x); for (var i=0; i<np; i++) { let p=lighting.point_lights[i]; let pv=p.position.xyz-wp; let pd=length(pv); if pd>p.position.w{continue;} let pL=pv/pd; let pa=1.0/(pd*pd+0.01); let pf=saturate(1.0-pd/p.position.w); Lo+=eval_light(N,V,pL,p.color.rgb*p.color.a*pa*pf,alb,met,rou,F0); } let ns = i32(lighting.num_spot_lights.x); for (var i=0; i<ns; i++) { let s=lighting.spot_lights[i]; let sv=wp-s.position.xyz; let sd=length(sv); if sd>s.position.w{continue;} let sL=-normalize(sv); let sc=dot(normalize(sv),normalize(s.direction.xyz)); let ca=saturate((sc-s.cone.y)/(s.cone.x-s.cone.y)); let sa=1.0/(sd*sd+0.01); let sf=saturate(1.0-sd/s.position.w); Lo+=eval_light(N,V,sL,s.color.rgb*s.color.a*sa*sf*ca,alb,met,rou,F0); } let amb = lighting.ambient_color.rgb*lighting.ambient_color.w*alb*ao; var color = amb+Lo; if ef > 0.5 { color += alb; } return vec4<f32>(color, 1.0); }
